import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';

const base=process.env.GAME_URL||'http://127.0.0.1:5173';
const output=new URL('../artifacts/',import.meta.url);
await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||undefined,args:['--enable-webgl','--ignore-gpu-blocklist',...(process.platform==='darwin'?['--use-angle=metal']:[])]});
const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});
const errors=[];
async function capture(name){await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(420);await page.screenshot({path:new URL(name,output).pathname});}
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto(base+'/?test=1',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.game?.getState().ready);
await page.waitForSelector('#loading',{state:'detached'});
await capture('01-arrival.png');
const report={arrival:await page.evaluate(()=>game.getState())};
await page.keyboard.press('KeyE');
report.enter=await page.evaluate(()=>game.getState());
await page.evaluate(()=>game.step(3,{forward:1}));
report.driving=await page.evaluate(()=>game.getState());
await capture('02-driving.png');
await page.evaluate(()=>game.step(.7,{forward:1,steer:1,brake:true}));
report.drift=await page.evaluate(()=>game.getState());
await capture('03-drift.png');
await page.evaluate(()=>{game.scenario('coast');game.step(1.5,{forward:1});});
await capture('04-coast.png');
report.coast=await page.evaluate(()=>game.getState());
await page.evaluate(()=>{game.scenario('crash');game.step(.8,{forward:1});});
report.crash=await page.evaluate(()=>game.getState());
await capture('05-crash.png');
await page.evaluate(()=>game.interact());
report.exit=await page.evaluate(()=>game.getState());
await capture('06-exit.png');
await page.evaluate(()=>{game.scenario('ramp');game.step(1.25,{forward:1});});
report.ramp=await page.evaluate(()=>game.getState());
await capture('07-ramp.png');
await page.keyboard.press('Escape');
await capture('08-pause.png');
await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>game.scenario('walking'));
await capture('09-mobile.png');
await page.setViewportSize({width:1440,height:960});
await page.evaluate(()=>{game.scenario('driving');game.camera(2);});
await capture('10-city-overview.png');
report.errors=errors;
await writeFile(new URL('capture-report.json',output),JSON.stringify(report,null,2));
console.log(JSON.stringify({screenshots:10,output:output.pathname,errors,drivingKph:report.driving.vehicle.speedKph,wrecked:report.crash.vehicle.wrecked,rampHeight:report.ramp.vehicle.y},null,2));
await browser.close();
if(errors.length)process.exitCode=1;
